#!/usr/bin/env bash
set -euo pipefail

echo "[secrets] Starting LocalStack Secrets Manager initialization..."

# Region defaults for LocalStack
AWS_REGION=${AWS_DEFAULT_REGION:-us-east-1}
ACCOUNT_ID="000000000000"

# Helper function to create or update a secret
create_or_update_secret() {
  local secret_name="$1"
  local secret_value="$2"
  
  echo "[secrets] Ensuring secret: ${secret_name}"
  
  # Try to create the secret first
  if awslocal secretsmanager create-secret \
    --name "${secret_name}" \
    --secret-string "${secret_value}" \
    --region "$AWS_REGION" \
    >/dev/null 2>&1; then
    echo "[secrets] Created secret: ${secret_name}"
  else
    # Secret already exists, update it
    if awslocal secretsmanager update-secret \
      --secret-id "${secret_name}" \
      --secret-string "${secret_value}" \
      --region "$AWS_REGION" \
      >/dev/null 2>&1; then
      echo "[secrets] Updated secret: ${secret_name}"
    else
      echo "[secrets] Warning: Could not create or update secret: ${secret_name}"
    fi
  fi
}

# ============================================================================
# DATABASE SECRETS
# ============================================================================
echo "[secrets] Configuring database connection secrets..."

# SECURITY: Store database connection string in Secrets Manager
# 
# Local Development:
# - For simplicity, we use a consistent default password that matches docker-compose.yml
# - The connection string (including password) is stored in Secrets Manager
# - The application retrieves it from Secrets Manager, not from environment variables
# - No plain text password files are used
#
# Production:
# - Password is generated by AWS RDS and stored in AWS Secrets Manager
# - Application retrieves connection string from AWS Secrets Manager
# - No hardcoded passwords anywhere
#
# See: docs/security.md § Secrets Management
# See: technical-decisions.md § 3.1 Configuration-First Principle

# For local development, use the same password as configured in docker-compose.yml
# This ensures consistency between the database container and Secrets Manager
# In production, this would be retrieved from AWS Secrets Manager or RDS
DB_PASSWORD="postgres"

# Build connection string - this is stored ONLY in Secrets Manager
# The application retrieves this at startup - no plain text files involved
DATABASE_CONNECTION_STRING="Host=db;Port=5432;Database=transactionprocessor;Username=postgres;Password=${DB_PASSWORD};Include Error Detail=true"

create_or_update_secret \
  "TransactionProcessor/Database/ConnectionString" \
  "${DATABASE_CONNECTION_STRING}"

echo "[secrets] Database connection string stored in Secrets Manager"
echo "[secrets] SECURITY: No plain text password files used - all secrets in Secrets Manager"

# ============================================================================
# AWS S3 SECRETS
# ============================================================================
echo "[secrets] Configuring AWS S3 secrets..."

# Create S3 secrets as a JSON object for easier retrieval
S3_SECRETS=$(cat <<EOF
{
  "BucketName": "cnab-files",
  "AccessKeyId": "test",
  "SecretAccessKey": "test",
  "Region": "us-east-1"
}
EOF
)

create_or_update_secret \
  "TransactionProcessor/AWS/S3" \
  "${S3_SECRETS}"

# Also create individual secrets for backward compatibility
create_or_update_secret \
  "TransactionProcessor/AWS/S3/BucketName" \
  "cnab-files"

create_or_update_secret \
  "TransactionProcessor/AWS/S3/AccessKeyId" \
  "test"

create_or_update_secret \
  "TransactionProcessor/AWS/S3/SecretAccessKey" \
  "test"

create_or_update_secret \
  "TransactionProcessor/AWS/S3/Region" \
  "us-east-1"

# ============================================================================
# AWS SQS SECRETS
# ============================================================================
echo "[secrets] Configuring AWS SQS secrets..."

# Create SQS secrets as a JSON object
# Use 'localstack' hostname for Docker container networking (not 'localhost')
# Containers access LocalStack via the service name 'localstack' in docker-compose
SQS_SECRETS=$(cat <<EOF
{
  "QueueUrl": "http://localstack:4566/000000000000/file-processing-queue",
  "DlqUrl": "http://localstack:4566/000000000000/file-processing-dlq",
  "Region": "us-east-1"
}
EOF
)

create_or_update_secret \
  "TransactionProcessor/AWS/SQS" \
  "${SQS_SECRETS}"

# Also create individual secrets for backward compatibility
create_or_update_secret \
  "TransactionProcessor/AWS/SQS/QueueUrl" \
  "http://localstack:4566/000000000000/file-processing-queue"

create_or_update_secret \
  "TransactionProcessor/AWS/SQS/DlqUrl" \
  "http://localstack:4566/000000000000/file-processing-dlq"

create_or_update_secret \
  "TransactionProcessor/AWS/SQS/Region" \
  "us-east-1"

# ============================================================================
# OAUTH SECRETS (Optional - for development)
# ============================================================================
echo "[secrets] Configuring OAuth secrets (optional)..."

# Create OAuth secrets as a JSON object (for development/testing only)
OAUTH_SECRETS=$(cat <<EOF
{
  "ClientId": "test-client-id",
  "ClientSecret": "test-client-secret",
  "Authority": "http://localhost:4566/cognito",
  "Audience": "transaction-processor-api"
}
EOF
)

create_or_update_secret \
  "TransactionProcessor/OAuth" \
  "${OAUTH_SECRETS}"

# ============================================================================
# VERIFICATION
# ============================================================================
echo "[secrets] Verifying created secrets..."

# List all secrets for TransactionProcessor
echo "[secrets] Available secrets:"
awslocal secretsmanager list-secrets \
  --query "SecretList[?starts_with(Name, 'TransactionProcessor/')].Name" \
  --output table \
  2>/dev/null || echo "[secrets] Warning: Could not list secrets"

echo "[secrets] LocalStack Secrets Manager initialization complete."
echo "[secrets] All secrets are now available for the TransactionProcessor API."
